<a href="https://colab.research.google.com/github/2403a54098-boop/ML-LAB/blob/main/mllab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# New Section

In [ ]:
df=pd.read_csv('/content/Salary_dataset.csv')
df

Unnamed: 0  YearsExperience    Salary
0            0              1.2   39344.0
1            1              1.4   46206.0
2            2              1.6   37732.0
3            3              2.1   43526.0
4            4              2.3   39892.0
5            5              3.0   56643.0
6            6              3.1   60151.0
7            7              3.3   54446.0
8            8              3.3   64446.0
9            9              3.8   57190.0
10          10              4.0   63219.0
11          11              4.1   55795.0
12          12              4.1   56958.0
13          13              4.2   57082.0
14          14              4.6   61112.0
15          15              5.0   67939.0
16          16              5.2   66030.0
17          17              5.4   83089.0
18          18              6.0   81364.0
19          19              6.1   93941.0
20          20              6.9   91739.0
21          21              7.2   98274.0
22          22              8.0  101303.0
23          23              8.3  113813.0
24          24              8.8  109432.0
25          25              9.1  105583.0
26          26              9.6  116970.0
27          27              9.7  112636.0
28          28             10.4  122392.0
29          29             10.6  121873.0

In [ ]:
df.head()

Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

In [ ]:
df.tail()

Unnamed: 0  YearsExperience    Salary
25          25              9.1  105583.0
26          26              9.6  116970.0
27          27              9.7  112636.0
28          28             10.4  122392.0
29          29             10.6  121873.0

In [ ]:
x=df.YearsExperience
y=df.Salary
x

0      1.2
1      1.4
2      1.6
3      2.1
4      2.3
5      3.0
6      3.1
7      3.3
8      3.3
9      3.8
10     4.0
11     4.1
12     4.1
13     4.2
14     4.6
15     5.0
16     5.2
17     5.4
18     6.0
19     6.1
20     6.9
21     7.2
22     8.0
23     8.3
24     8.8
25     9.1
26     9.6
27     9.7
28    10.4
29    10.6
Name: YearsExperience, dtype: float64

In [ ]:
x=df['YearsExperience'].values
y=df['Salary'].values
x


array([ 1.2,  1.4,  1.6,  2.1,  2.3,  3. ,  3.1,  3.3,  3.3,  3.8,  4. ,
        4.1,  4.1,  4.2,  4.6,  5. ,  5.2,  5.4,  6. ,  6.1,  6.9,  7.2,
        8. ,  8.3,  8.8,  9.1,  9.6,  9.7, 10.4, 10.6])

In [ ]:
y

array([ 39344.,  46206.,  37732.,  43526.,  39892.,  56643.,  60151.,
        54446.,  64446.,  57190.,  63219.,  55795.,  56958.,  57082.,
        61112.,  67939.,  66030.,  83089.,  81364.,  93941.,  91739.,
        98274., 101303., 113813., 109432., 105583., 116970., 112636.,
       122392., 121873.])

In [ ]:
x= df.iloc[:,1].values
x

array([ 1.2,  1.4,  1.6,  2.1,  2.3,  3. ,  3.1,  3.3,  3.3,  3.8,  4. ,
        4.1,  4.1,  4.2,  4.6,  5. ,  5.2,  5.4,  6. ,  6.1,  6.9,  7.2,
        8. ,  8.3,  8.8,  9.1,  9.6,  9.7, 10.4, 10.6])

In [ ]:
Y= df.iloc[:,-1].values
Y

array([ 39344.,  46206.,  37732.,  43526.,  39892.,  56643.,  60151.,
        54446.,  64446.,  57190.,  63219.,  55795.,  56958.,  57082.,
        61112.,  67939.,  66030.,  83089.,  81364.,  93941.,  91739.,
        98274., 101303., 113813., 109432., 105583., 116970., 112636.,
       122392., 121873.])

In [ ]:
import numpy as np

In [ ]:
X=np.array(x)
Y=np.array(y)

In [ ]:
reshape=X.reshape(-1,1)
reshape

array([[ 1.2],
       [ 1.4],
       [ 1.6],
       [ 2.1],
       [ 2.3],
       [ 3. ],
       [ 3.1],
       [ 3.3],
       [ 3.3],
       [ 3.8],
       [ 4. ],
       [ 4.1],
       [ 4.1],
       [ 4.2],
       [ 4.6],
       [ 5. ],
       [ 5.2],
       [ 5.4],
       [ 6. ],
       [ 6.1],
       [ 6.9],
       [ 7.2],
       [ 8. ],
       [ 8.3],
       [ 8.8],
       [ 9.1],
       [ 9.6],
       [ 9.7],
       [10.4],
       [10.6]])

In [ ]:
X.max()

np.float64(10.6)

In [ ]:
X_std=X.std()
X_standartedized=(X-X.mean())/X.std()
X_standartedized

array([-1.51005294, -1.43837321, -1.36669348, -1.18749416, -1.11581443,
       -0.86493538, -0.82909552, -0.75741579, -0.75741579, -0.57821647,
       -0.50653674, -0.47069688, -0.47069688, -0.43485702, -0.29149756,
       -0.1481381 , -0.07645838, -0.00477865,  0.21026054,  0.2461004 ,
        0.53281931,  0.6403389 ,  0.92705781,  1.03457741,  1.21377673,
        1.32129632,  1.50049564,  1.5363355 ,  1.78721455,  1.85889428])

In [ ]:
X_norm=(X-X.min())/(X.max()-X.min())
X_norm

array([0.        , 0.0212766 , 0.04255319, 0.09574468, 0.11702128,
       0.19148936, 0.20212766, 0.22340426, 0.22340426, 0.27659574,
       0.29787234, 0.30851064, 0.30851064, 0.31914894, 0.36170213,
       0.40425532, 0.42553191, 0.44680851, 0.5106383 , 0.5212766 ,
       0.60638298, 0.63829787, 0.72340426, 0.75531915, 0.80851064,
       0.84042553, 0.89361702, 0.90425532, 0.9787234 , 1.        ])

In [ ]:
n = np.random.randn()
c = np.random.randn()
print(n)
print(c)

-0.3131426356560278
-0.736689267669672


In [ ]:
def predict(X,m,c):
  y_pred=m*x+c
  return y_pred


In [ ]:
y_pred =predict(X_norm,n,c)


In [ ]:
print(y_pred[:5])


[-1.11246043 -1.17508896 -1.23771748 -1.3942888  -1.45691733]


In [ ]:
def compute_cost(y,y_pred):
  n = len(y)
  cost = (1/(2*n))*np.sum((y-y_pred)**2)
  return cost

In [ ]:
cost = compute_cost(Y,y_pred)
print("intial cost:", cost)

intial cost: 3251761509.0966725


In [ ]:
m=0.0
c=0.0
y_pred =predict(X_norm,n,c)
cost = compute_cost(Y,y_pred)
print("intial cost:", cost)

intial cost: 3251553638.866667


In [ ]:
learning_rate=0.01
epochs =1000
print("learning rate",learning_rate)
print("epochs",epochs)

learning rate 0.01
epochs 1000


In [ ]:
n=len(y)
n

30

In [ ]:
cost_History=[]

In [ ]:
for epoch in range(epochs):
  #step1
  y_pred = predict(X_norm,m,c)
  #step2
  dn = (1/n)*np.sum((y_pred-Y)*X_norm)
  dc = (1/n)*np.sum(y_pred-Y)
  #step3
  n_m = m-learning_rate*dn
  n_c = c-learning_rate*dc
  #step4
  m=n_m
  c=n_c
  #step5
  cost = compute_cost(Y,y_pred)
  cost_History.append(cost)
  if epoch%100==0:
    print("epoch is",epoch,"cost is",cost)

epoch is 0 cost is 15707290.56868116
epoch is 100 cost is 15683164.399212135
epoch is 200 cost is 15667143.422581473
epoch is 300 cost is 15656504.697170483
epoch is 400 cost is 15649440.054297587
epoch is 500 cost is 15644748.780014863
epoch is 600 cost is 15641633.540534023
epoch is 700 cost is 15639564.866558013
epoch is 800 cost is 15638191.164136302
epoch is 900 cost is 15637278.957396476


In [ ]:
final_slope=n
final_intercept=c
print("final slope",final_slope)
print("final intercept",final_intercept)

final slope 30
final intercept 24741.40248825


In [ ]:
def predict_salary(YearsExperience,m,c,x_min,x_max):
  x=np.array(YearsExperience)
  x_n=(x-x_min)/(x_max-x_min)
  sal_pred=m*x_n+c
  return sal_pred

In [ ]:
years=5
predicted_salary=predict_salary(
    years,
    final_slope,
    final_intercept,
    X.min(),
    X.max())
print(f"predicted salary for {years} years of experience")
print(f"predicted salary is {predicted_salary}")


predicted salary for 5 years of experience
predicted salary is 24753.53014782447
